In [45]:
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET

In [2]:
x = np.array([0,1,2,3])
x

array([0, 1, 2, 3])

In [3]:
w = np.array([[0,1,2,3],[4,5,6,7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
y=np.arange(8).reshape(2,4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
print(np.square(x))

[0 1 4 9]


In [7]:
print(np.sqrt(x))

[ 0.          1.          1.41421356  1.73205081]


In [8]:
print(np.cos(x))

[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [9]:
print(np.max(x))

3


In [10]:
print(np.min(x))

0


In [11]:
print(np.mean(x))

1.5


In [12]:
print(np.std(x))

1.11803398875


In [15]:
my_array = np.array([[0,1,2,3],[4,5,6,7]])
df = pd.DataFrame(my_array)
df

0  1  2  3
0  0  1  2  3
1  4  5  6  7

In [16]:
df.columns = ['first', 'this', 'that', 'last']
df.index = ['row_1', 'row_2']
df

first  this  that  last
row_1      0     1     2     3
row_2      4     5     6     7

In [18]:
df2 = pd.DataFrame(
my_array,
columns=['first', 'this', 'that', 'last'],
index=['row_1', 'row_2'])
df2

first  this  that  last
row_1      0     1     2     3
row_2      4     5     6     7

In [20]:
names = ['George',
       'John',
       'Thomas',
       'James',
       'Andrew',
       'Martin',
       'William',
       'Zachary',
       'Millard',
       'Franklin']

purchases = pd.DataFrame(index=names)

purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] =  [2, 1, 0, 8, 0, 5, 7, 3, 0 , 5]
purchases

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [21]:
purchases['items_purch_per_ad'] = purchases['items_purchased']/purchases['ad_views']

In [22]:
purchases['items_purchased']/purchases['ad_views']

George      0.125000
John        0.023810
Thomas      0.000000
James       0.615385
Andrew      0.000000
Martin      0.263158
William     0.107692
Zachary     0.130435
Millard     0.000000
Franklin    0.064935
dtype: float64

In [23]:
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        42                1            0.023810
Thomas       CAN        32                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        63                0            0.000000
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Millard      CAN        16                0            0.000000
Franklin      US        77                5            0.064935

In [24]:
purchases['country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [25]:
purchases.loc['George']

country                  US
ad_views                 16
items_purchased           2
items_purch_per_ad    0.125
Name: George, dtype: object

In [26]:
purchases.loc[:,'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [27]:
purchases.loc['George', 'country']

'US'

In [28]:
purchases.iloc[1:3, 1]

John      42
Thomas    32
Name: ad_views, dtype: int64

In [29]:
purchases.loc[lambda df: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [30]:
purchases[purchases['items_purchased'] > 1 ]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [31]:
purchases.groupby('country')

In [32]:
purchases.groupby('country').mean()

ad_views  items_purchased  items_purch_per_ad
country                                               
CAN         38.25             0.25            0.005952
US          35.50             5.00            0.217767

In [34]:
df = pd.read_csv('purchases.csv')
print(df)

  Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5


In [38]:
df.to_csv('newPurchases.csv')

In [39]:
df = pd.read_json('purchases.json')

In [40]:
df

Unnamed: 0  ad_views country  items_purchased
0     George        16      US                2
1       John        42     CAN                1
2     Thomas        32     CAN                0
3      James        13      US                8
4     Andrew        63     CAN                0
5     Martin        19      US                5
6    William        65      US                7
7    Zachary        23      US                3
8    Millard        16     CAN                0
9   Franklin        77      US                5

In [41]:
df.to_json('my_data.json')

In [42]:
serialized_purchases = df.to_json()

In [43]:
serialized_purchases

'{"Unnamed: 0":{"0":"George","1":"John","2":"Thomas","3":"James","4":"Andrew","5":"Martin","6":"William","7":"Zachary","8":"Millard","9":"Franklin"},"ad_views":{"0":16,"1":42,"2":32,"3":13,"4":63,"5":19,"6":65,"7":23,"8":16,"9":77},"country":{"0":"US","1":"CAN","2":"CAN","3":"US","4":"CAN","5":"US","6":"US","7":"US","8":"CAN","9":"US"},"items_purchased":{"0":2,"1":1,"2":0,"3":8,"4":0,"5":5,"6":7,"7":3,"8":0,"9":5}}'

In [46]:
tree = ET.parse('purchases.xml')

In [47]:
root = tree.getroot()

In [48]:
def xml_to_list(root):
    result=[]
    for row in root:
        row_list = []
        for column in row:
            row_list.append(column.text)
        result.append(row_list)
    return result

In [50]:
df = pd.DataFrame(xml_to_list(root))
print(df)

          0    1   2  3
0    George   US  16  2
1      John  CAN  42  1
2    Thomas  CAN  32  0
3     James   US  13  8
4    Andrew  CAN  63  0
5    Martin   US  19  5
6   William   US  65  7
7   Zachary   US  23  3
8   Millard  CAN  16  0
9  Franklin   US  77  5


In [53]:
with open('poem.txt') as poem_file:
    text = poem_file.readlines()
    print('This file is {} lines long'.format(len(text)))
    for line in text:
        print(line)

This file is 19 lines long
Beautiful is better than ugly.

Explicit is better than implicit.

Simple is better than complex.

Complex is better than complicated.

Flat is better than nested.

Sparse is better than dense.

Readability counts.

Special cases aren't special enough to break the rules.

Although practicality beats purity.

Errors should never pass silently.

Unless explicitly silenced.

In the face of ambiguity, refuse the temptation to guess.

There should be one-- and preferably only one --obvious way to do it.

Although that way may not be obvious at first unless you're Dutch.

Now is better than never.

Although never is often better than *right* now.

If the implementation is hard to explain, it's a bad idea.

If the implementation is easy to explain, it may be a good idea.

Namespaces are one honking great idea -- let's do more of those!
